development:
  pwdless_user: ip_admin
  dhcpd_dir: /etc/dhcpd
  arping_path: /usr/bin/arping

test:
  pwdless_user: ip_admin
  dhcpd_dir: /etc/dhcpd
  arping_path: /usr/bin/arping

production:
  pwdless_user: ip_admin
  dhcpd_dir: /etc/dhcpd
  arping_path: /usr/bin/arping
